name=M590Driver
version=1.0.0
author=Aleksander Kirikov
maintainer=Aleksander Kirikov
sentence=Lightweight asynchronous driver for the M590 GSM modem.
paragraph=Non-blocking Arduino driver for the M590 GSM modem based on a finite state machine (FSM). Designed for reliable embedded systems without using delay().
category=Communication
url=https://github.com/kirikow75-dev/M590Driver
architectures=*




