name: Compile Examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile Arduino sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            examples/BasicUsage
            examples/SendSMS       
            examples/ReceiveSMS
            examples/SendCall
            examples/ReceiveCall
            examples/UserCommands
            examples/SleepMode
            examples/HardwareReset
            examples/FullInit
          
